Build Fixes + Config Improvements
slaclab/cpsw pull request #15
Opened 2024-07-15 20:10 UTC by JJL772

* Reverted the previous fix applied by #8, it causes build errors with boost python. It seems the build error only occurs on python 3.10+, so I can't reproduce this in S3DF yet either (our current conda env is v2.4 for python 3.8). Going to just revert it for now and address the issue later at some point.
* Link against libboost_python3 instead of libboost_python
* Fix missing semicolon in yaml_cpp_python.cc. I don't know how this ever compiled.....
* Improved portability of config.mak by replacing absolute AFS paths with variables instead.

2024-07-17 20:55 UTC, JJL772 commented
Confirmed working in S3DF and on the legacy AFS environment. Tested all supported target architectures.

2024-07-24 21:40 UTC, ernestow commented
Looks good for now

2024-07-24 22:38 UTC, marciodo requested changes

2024-07-24 22:38 UTC, marciodo commented on config.mak
Can you use the same ifeq PACKAGE_TOP structure that you used for the other packages?

I don't remember if you fixed this: will this makefile allow us to build in any host architecture with the rhel#-x86_64 format without need to use "make HARCH=something"?

2024-07-24 23:21 UTC, JJL772 commented on config.mak
> Can you use the same ifeq PACKAGE_TOP structure that you used for the other packages?

Sure.

> I don't remember if you fixed this: will this makefile allow us to build in any host architecture with the rhel#-x86_64 format without need to use "make HARCH=something"?

Yes, this was fixed by #9. It's pretty easy to build CPSW now.

2024-07-25 00:52 UTC, marciodo approved these changes

2024-07-25 00:52 UTC, merged